[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vuln-analyzer"
version = "0.1.0"
description = "Simple ML + rule-based code vulnerability analyzer"
authors = [
    { name = "your-name" }
]
dependencies = [
    "pandas",
    "scikit-learn"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]